// publications
export const LOAD_PUBLICATIONS = 'LOAD_PUBLICATIONS';
export const PUBLICATIONS_ERROR = 'PUBLICATIONS_ERROR';

// publication
export const PUBLICATION_BY_ID = 'PUBLICATION_BY_ID';
export const PUBLICATION_ERROR = 'PUBLICATION_ERROR';
